#!/bin/zsh
xsetroot -solid "#1d2433"
export GTK_IM_MODULE='ibus'
export QT_IM_MODULE='ibus'
export GLFW_IM_MODULE='ibus'
export XMODIFIERS='@im=ibus'
export GTK_THEME=Adwaita:dark
export MOZC_IBUS_CANDIDATE_WINDOW=ibus
